name: "IoT Network Checker"
description: "Checking / monitoring network devices by Ping"
version: "1.4.0"
slug: "iot_checker"
init: false
arch:
  - aarch64
  - amd64
startup: services
mqtt: true
services:
  - mqtt:need
options:
  mqtt_user: "MQTT Name"
  mqtt_password: "MQTT Password"
  devices:
    - name: "Example Router"
      ip: "192.168.2.1"
schema:
  mqtt_user: str
  mqtt_password: str
  devices:
    - name: str
      ip: str
